# Generated by Django 2.2.7 on 2019-11-29 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=True)),
                ('caller_number', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('ucid', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallLeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_number', models.CharField(max_length=128)),
                ('cdr_id', models.CharField(max_length=128, unique=True)),
                ('dialed_number', models.CharField(max_length=128)),
                ('duration', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('ucid', models.CharField(max_length=128)),
                ('vdn', models.CharField(blank=True, max_length=128, null=True)),
                ('call', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.Call')),
            ],
        ),
    ]
